# Generated by Django 4.2.2 on 2025-04-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_rename_name_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_plan',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
